#!/usr/bin/env python3
"""Vendor language-probe label and status bitmaps for the boot
sequence opening beats.

Renders eight short strings (four labels, four statuses) using GNU
Unifont via ImageMagick `convert`, packs each as a row-major
1-bit bitmap, and emits them as Rust constants in `src/probes.rs`.

Pipeline per string:
  1. `convert -font unifont.otf -pointsize 16 +antialias label:'<text>'
     -threshold 50% -depth 1 out.pbm`.
  2. Parse the PBM header to discover the actual rendered width.
  3. Crop to the first 16 rows. Unifont at pointsize 16 emits 17-row
     output via ImageMagick `label:`; the 17th row is blank padding.
  4. Pack each row MSB-leftmost into bytes, padded to the next byte
     boundary. Storage matches `src/logo.rs` so the renderer can
     consume both via the same blit primitive.

Usage:
  vendor-language-probes.py > src/probes.rs

Apt prerequisite:
  sudo apt install fonts-unifont imagemagick

GNU Unifont is BSD-2-Clause / dual-licensed under SIL OFL; see
`LICENSES/FONT_UNIFONT.txt` (added alongside this script).
"""

import subprocess
import sys
import tempfile
from pathlib import Path


UNIFONT = '/usr/share/fonts/opentype/unifont/unifont.otf'

CELL_HEIGHT = 16

# (rust_name_prefix, label_text, status_text). These lines render
# at the top of BOOT_SCRIPT, ahead of the ASCII telemetry. Only
# scripts spleen cannot represent live here; Latin-script probes
# (Spanish, English) go through the spleen telemetry path directly
# and are not vendored as bitmaps.
PROBES = [
    ('MANDARIN', '检测中文支持', '失败'),
    ('HINDI', 'हिन्दी समर्थन की जाँच', 'विफल'),
]


def rasterise(text: str, out_pbm: Path) -> None:
    subprocess.check_call([
        'convert',
        '-font', UNIFONT,
        '-pointsize', '16',
        '+antialias',
        '-background', 'white',
        '-fill', 'black',
        f'label:{text}',
        '-depth', '1',
        '-threshold', '50%',
        str(out_pbm),
    ])


def parse_pbm(path: Path) -> tuple[int, int, list[list[int]]]:
    """Return (width, height, rows) where rows are 0/1 pixel lists.

    PBM raw 'P4' format: bit value 1 = foreground (black), 0 =
    background. We threshold at 50% during rasterise so the input
    is already binary; this just unpacks bits to 0/1 lists.
    """
    data = path.read_bytes()
    if not data.startswith(b'P4'):
        raise SystemExit(f'{path}: not a raw PBM')
    idx = data.index(b'\n', 0) + 1
    while data[idx:idx + 1] == b'#':
        idx = data.index(b'\n', idx) + 1
    end = data.index(b'\n', idx)
    width, height = (int(x) for x in data[idx:end].decode().split())
    payload = data[end + 1:]
    row_bytes = (width + 7) // 8
    rows = []
    for r in range(height):
        row = []
        for c in range(width):
            byte = payload[r * row_bytes + c // 8]
            bit = (byte >> (7 - (c % 8))) & 1
            row.append(bit)
        rows.append(row)
    return width, height, rows


def normalise_to_cell_height(rows: list[list[int]], width: int) -> list[list[int]]:
    """Take the first CELL_HEIGHT rows; pad with blank rows if shorter."""
    if len(rows) >= CELL_HEIGHT:
        return rows[:CELL_HEIGHT]
    return rows + [[0] * width for _ in range(CELL_HEIGHT - len(rows))]


def pack_rows(rows: list[list[int]], width: int) -> list[int]:
    """Row-major MSB-leftmost packing, padded to byte boundary per row."""
    out = []
    row_bytes = (width + 7) // 8
    for row in rows:
        for chunk_start in range(0, row_bytes * 8, 8):
            byte = 0
            for i in range(8):
                c = chunk_start + i
                if c < width and row[c]:
                    byte |= 1 << (7 - i)
            out.append(byte)
    return out


def emit_const(name: str, packed: list[int], width: int, trailing_blank: bool = True) -> None:
    n = len(packed)
    # `rustfmt::skip` preserves the row-per-line layout below, which is
    # what makes the bitmaps visually inspectable in the source.
    print('#[rustfmt::skip]')
    print(f'pub const PROBE_{name}_BITMAP: [u8; {n}] = [')
    row_bytes = (width + 7) // 8
    for r in range(CELL_HEIGHT):
        hex_bytes = ', '.join(
            f'0x{b:02X}' for b in packed[r * row_bytes:(r + 1) * row_bytes]
        )
        print(f'    {hex_bytes},')
    print('];')
    print(f'pub const PROBE_{name}_WIDTH_PX: usize = {width};')
    if trailing_blank:
        print()


def main() -> None:
    if not Path(UNIFONT).exists():
        sys.stderr.write(
            f'{UNIFONT}: not found. Install via `apt install fonts-unifont`.\n'
        )
        sys.exit(1)

    print(
        '// Language-probe label and status bitmaps for the boot-sequence\n'
        '// opening beats. Generated by scripts/vendor-language-probes.py;\n'
        '// do not edit by hand. Regenerate via `make vendor-probes` after\n'
        '// editing the PROBES table at the top of the vendor script.\n'
        '//\n'
        '// Source font: GNU Unifont, used under SIL OFL 1.1\n'
        '// (`apt install fonts-unifont`). Rendered via ImageMagick at\n'
        '// pointsize 16 with anti-aliasing disabled, then cropped to\n'
        '// 16 rows so each bitmap is exactly one renderer cell tall.\n'
        '// Storage is row-major MSB-leftmost packed bits; each row is\n'
        '// padded to the next byte boundary so the renderer can consume\n'
        '// these via the same blit primitive as src/logo.rs.\n'
    )

    flat = [
        (f'{name}_{kind}', text)
        for name, label, status in PROBES
        for kind, text in [('LABEL', label), ('STATUS', status)]
    ]
    with tempfile.TemporaryDirectory() as tmpdir:
        for i, (const_name, text) in enumerate(flat):
            pbm = Path(tmpdir) / f'{const_name}.pbm'
            rasterise(text, pbm)
            width, _height, rows = parse_pbm(pbm)
            rows = normalise_to_cell_height(rows, width)
            packed = pack_rows(rows, width)
            # Drop the trailing blank line on the very last entry so
            # the file ends exactly with `];\npub const ...PX: usize = N;\n`
            # and end-of-file-fixer is happy.
            emit_const(const_name, packed, width, trailing_blank=(i < len(flat) - 1))


if __name__ == '__main__':
    main()
