#!/usr/bin/env python3
"""Parse a BDF bitmap font and emit a Rust const array for ASCII glyphs 0x00-0x7F.

Usage: vendor-font.py <path-to-bdf> > src/renderer/font.rs
"""

import sys


def parse_bdf(path):
    """Return a dict mapping encoding (int) -> list of 16 ints (bitmap rows)."""
    glyphs = {}
    with open(path) as f:
        lines = f.readlines()

    i = 0
    while i < len(lines):
        line = lines[i].rstrip()
        if line == 'STARTCHAR' or line.startswith('STARTCHAR '):
            encoding = None
            bitmap_rows = []
            in_bitmap = False
            i += 1
            while i < len(lines):
                tok = lines[i].rstrip()
                if tok == 'ENDCHAR':
                    break
                if tok.startswith('ENCODING '):
                    encoding = int(tok.split()[1])
                elif tok == 'BITMAP':
                    in_bitmap = True
                elif in_bitmap:
                    bitmap_rows.append(int(tok, 16))
                i += 1
            if encoding is not None and 0x00 <= encoding <= 0x7F:
                if encoding in glyphs:
                    print(
                        f'error: duplicate ENCODING {encoding} in BDF',
                        file=sys.stderr,
                    )
                    sys.exit(1)
                if len(bitmap_rows) != 16:
                    print(
                        f'error: ENCODING {encoding} has {len(bitmap_rows)} '
                        f'bitmap rows, expected 16',
                        file=sys.stderr,
                    )
                    sys.exit(1)
                glyphs[encoding] = bitmap_rows
        i += 1
    return glyphs


def main():
    if len(sys.argv) != 2:
        print(f'usage: {sys.argv[0]} <spleen-8x16.bdf>', file=sys.stderr)
        sys.exit(1)

    glyphs = parse_bdf(sys.argv[1])

    print('// Spleen 8x16 bitmap font — ASCII codepoints U+0000..U+007F.')
    print('// Source: https://github.com/fcambus/spleen')
    print('//   raw file: spleen-8x16.bdf')
    print('//   upstream commit: 4cde2e32c41bc7e05d9e2c2b7db3c43f7c7978d9')
    print('// License: BSD-2-Clause — see LICENSES/FONT_SPLEEN.txt')
    print('//')
    print('// Generated by scripts/vendor-font.py; do not edit by hand.')
    print('// Each entry is 16 bytes, one per pixel row, MSB = leftmost pixel.')
    print()
    print('#![allow(clippy::unreadable_literal)]')
    print()
    print('/// 8x16 bitmap font for ASCII U+0000..U+007F.')
    print('/// Row 0 is the topmost scanline; bit 7 of each byte is the leftmost pixel.')
    print('pub const FONT_8X16: [[u8; 16]; 128] = [')

    for cp in range(0x80):
        if cp in glyphs:
            row_hex = ', '.join(f'0x{b:02X}' for b in glyphs[cp])
            label = chr(cp) if 0x20 <= cp < 0x7F else f'U+{cp:04X}'
            print(f'    [{row_hex}], // {label}')
        else:
            zeros = ', '.join(['0x00'] * 16)
            print(f'    [{zeros}], // U+{cp:04X} (not defined)')

    print('];')


if __name__ == '__main__':
    main()
