#!/usr/bin/env python3
"""Vendor a monochrome, lightly-roughed-up bitmap of the Shaken Fist
logo for use as a BIOS-style mark in the top-right corner of the
boot sequence.

Pipeline:
  1. `convert` (ImageMagick) rasterises the SVG at 300 DPI, resizes
     to fit a 128x128 box, centres on a 128x128 white canvas, and
     thresholds to 1-bit. Phosphor-on = bright pixels from the
     source; the dark globe body becomes empty and the lighter
     details (continents, text) render in phosphor green.
  2. We load the resulting PBM, flip 2% of pixels pseudo-randomly
     with a fixed seed so the result is deterministic but the logo
     looks "aged" rather than pristine.
  3. We emit a Rust source file with WIDTH, HEIGHT, and a packed
     bit array (row-major, MSB-leftmost, one byte per 8 horizontal
     pixels).

Usage:
  vendor-logo.py <input.svg> > src/logo.rs
"""

import random
import subprocess
import sys
import tempfile
from pathlib import Path


WIDTH = 128
HEIGHT = 128
ROUGH_RATE = 0.02  # 2% of pixels flipped
RNG_SEED = 0x5EAFED


def rasterise(svg_path: Path, pbm_path: Path) -> None:
    subprocess.check_call([
        'convert',
        '-background', 'white',
        '-density', '300',
        str(svg_path),
        '-resize', f'{WIDTH}x{HEIGHT}',
        '-gravity', 'center',
        '-extent', f'{WIDTH}x{HEIGHT}',
        '-colorspace', 'Gray',
        '-threshold', '50%',
        str(pbm_path),
    ])


def parse_pbm(path: Path) -> list[list[int]]:
    """Return a 2D list of 0/1 pixels (rows × cols)."""
    data = path.read_bytes()
    # PBM 'raw' format: "P4\n<width> <height>\n<packed bits>"
    if not data.startswith(b'P4'):
        raise SystemExit(f'{path}: not a raw PBM')
    idx = 0
    # Skip "P4\n"
    idx = data.index(b'\n', idx) + 1
    # Skip comments
    while data[idx:idx + 1] == b'#':
        idx = data.index(b'\n', idx) + 1
    # Parse "<width> <height>\n"
    header_end = data.index(b'\n', idx)
    header = data[idx:header_end].decode('ascii')
    width, height = (int(x) for x in header.split())
    if (width, height) != (WIDTH, HEIGHT):
        raise SystemExit(f'expected {WIDTH}x{HEIGHT}, got {width}x{height}')
    payload = data[header_end + 1:]
    row_bytes = (width + 7) // 8
    pixels = []
    for r in range(height):
        row = []
        for c in range(width):
            byte = payload[r * row_bytes + c // 8]
            bit = (byte >> (7 - (c % 8))) & 1
            row.append(bit)
        pixels.append(row)
    return pixels


def rough_up(pixels: list[list[int]]) -> None:
    rng = random.Random(RNG_SEED)
    for r, row in enumerate(pixels):
        for c in range(len(row)):
            if rng.random() < ROUGH_RATE:
                row[c] ^= 1


def pack_rows(pixels: list[list[int]]) -> list[int]:
    """Pack to MSB-leftmost bytes, row-major."""
    out = []
    for row in pixels:
        for chunk_start in range(0, len(row), 8):
            byte = 0
            for i, bit in enumerate(row[chunk_start:chunk_start + 8]):
                byte |= bit << (7 - i)
            out.append(byte)
    return out


def emit_rust(packed: list[int]) -> None:
    print(
        '// Shaken Fist logo, monochrome, lightly roughed up for an aged-CRT feel.\n'
        '// Generated by scripts/vendor-logo.py; do not edit by hand.\n'
        '//\n'
        '// Source artwork: shakenfist-logo-small.svg in the repo root.\n'
        '// Rasterised at 300 DPI, resized to 128x128 inside a centred canvas,\n'
        '// thresholded at 50% grey, then 2% of pixels flipped via a PRNG\n'
        '// seeded to 0x5EAFED for reproducibility.\n'
        '//\n'
        '// Storage: row-major packed bits; bit 7 of each byte is the leftmost\n'
        '// pixel in that 8-pixel strip. Phosphor-on = 1.\n'
    )
    print(f'pub const LOGO_WIDTH: usize = {WIDTH};')
    print(f'pub const LOGO_HEIGHT: usize = {HEIGHT};')
    n = len(packed)
    print()
    print(f'pub const LOGO_BITMAP: [u8; {n}] = [')
    row_bytes = WIDTH // 8
    for r in range(HEIGHT):
        hex_bytes = ', '.join(
            f'0x{b:02X}' for b in packed[r * row_bytes:(r + 1) * row_bytes]
        )
        print(f'    {hex_bytes},')
    print('];')


def main() -> None:
    if len(sys.argv) != 2:
        print(f'usage: {sys.argv[0]} <input.svg>', file=sys.stderr)
        sys.exit(1)
    svg_path = Path(sys.argv[1])
    if not svg_path.exists():
        raise SystemExit(f'{svg_path}: not found')

    with tempfile.NamedTemporaryFile(suffix='.pbm') as tmp:
        pbm_path = Path(tmp.name)
        rasterise(svg_path, pbm_path)
        pixels = parse_pbm(pbm_path)

    rough_up(pixels)
    packed = pack_rows(pixels)
    emit_rust(packed)


if __name__ == '__main__':
    main()
